name: package_soapfilter_2_0
owner: peterli
description: Contains a tool dependency definition that downloads and extracts version
  2.0 of SOAPfilter.
homepage_url: http://soap.genomics.org.cn/index.html
long_description: |
    SOAPfilter is a tool for cleaning short reads.
remote_repository_url: https://github.com/gigascience/galaxy-bgisoap/tree/master/packages/package_soapfilter_2_0
type: tool_dependency_definition
categories:
- Tool Dependency Packages