name: package_msort_1_10
owner: peterli
description: Contains a tool dependency definition that downloads and extracts version
  1.0 of msort.
homepage_url: http://soap.genomics.org.cn/index.html
long_description: |
    msort sorts rows in text files by multiple fields.
remote_repository_url: https://github.com/gigascience/galaxy-bgisoap/tree/master/packages/package_msort_1_0
type: tool_dependency_definition
categories:
- Tool Dependency Packages